language: ruby
sudo: false
before_install: gem i bundler
cache: bundler
matrix:
  include:
    - rvm: 2.3.4
      gemfile: gemfiles/Gemfile.2_3
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.2_3
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.2_3
    - rvm: 2.6
      gemfile: gemfiles/Gemfile.2_3
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.jruby-19mode
    - rvm: jruby-9.1.13.0
      gemfile: gemfiles/Gemfile.jruby-9_1_5_0
      env:
        - JRUBY_OPTS='--debug'
addons:
  apt:
    packages:
    - bzr
    - subversion
    - git
    - mercurial
