language: ruby
sudo: false
before_install: gem i bundler
cache: bundler
matrix:
  include:
    - rvm: 2.3.4
    - rvm: 2.4.1
    - rvm: 2.5
    - rvm: 2.6
addons:
  apt:
    packages:
    - bzr
    - subversion
    - git
    - mercurial