language: ruby
sudo: false
before_install: gem install bundler:1.17.3
cache: bundler
matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
addons:
  apt:
    packages:
      - bzr
      - subversion
      - git
      - mercurial
